version: "3.8"

services:
  api_colmeia:
    build: ./api_simulador
    ports:
      - "8000:8000"
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  ingest_json:
    build: ./ingest_json
    volumes:
      - ./ingest_json/saida:/app/ingest_json/saida
    depends_on:
      - api_colmeia

  ingest_csv:
    build: ./ingest_csv
    volumes:
      - ./ingest_csv/saida:/app/ingest_csv/saida
    depends_on:
      - api_colmeia
      - kafka
    restart: unless-stopped

  ingest_db:
    build: ./ingest_db
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: colmeia
    depends_on:
      - api_colmeia
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: colmeia
    volumes:
      - mysql-data:/var/lib/mysql

#  airflow:
#    build: ./airflow
#    ports:
#      - "8080:8080"
#    depends_on:
#      - kafka
#      - mysql

#  dashboard:
#    build: ./dashboard
#    ports:
#      - "8501:8501"
#    depends_on:
#      - mysql

volumes:
  mysql-data: