version: "3.8"

services:
  api_colmeia:
    build: ./api_simulador
    ports:
      - "8000:8000"
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  ingest_json:
    build: ./ingest_json
    volumes:
      - ./ingest_json/saida:/app/ingest_json/saida
    depends_on:
      - api_colmeia

  ingest_csv:
    build: ./ingest_csv
    volumes:
      - ./ingest_csv/saida:/app/ingest_csv/saida
    depends_on:
      - api_colmeia
      - kafka
    restart: unless-stopped

  ingest_db:
    build: ./ingest_db
    command: consumer_db.py   # roda o script principal de ingestão
    volumes:
      - ./ingest_db/saida:/app/saida
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: colmeia
    depends_on:
      - api_colmeia
      - mysql
    restart: unless-stopped

  exportador_json:
    build: ./ingest_db
    command: exportador_json.py  # roda só exportador
    volumes:
      - ./ingest_db/saida:/app/saida
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: colmeia
    depends_on:
      - ingest_db
      - mysql
    restart: unless-stopped



  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: colmeia
    volumes:
      - mysql-data:/var/lib/mysql

  uploader_raw:
    build: ./datalake/uploader_raw
    depends_on:
      - ingest_json
      - ingest_csv
      - ingest_db
      - minio
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./ingest_json/saida:/app/ingest_json/saida
      - ./ingest_csv/saida:/app/ingest_csv/saida
      - ./ingest_db/saida:/app/ingest_db/saida

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    ports:
      - "8081:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          server:
            servlet:
              context-path: /
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: "kafka:9092"
    depends_on:
      - kafka

  processing_csv:
    build: ./datalake/processing_csv
    depends_on:
      - ingest_csv
      - minio
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./ingest_csv/saida:/app/ingest_csv/saida
      - ./datalake/processing_csv/saida:/app/processing_csv
    restart: unless-stopped

#  airflow:
#    build: ./airflow
#    ports:
#      - "8080:8080"
#    depends_on:
#      - kafka
#      - mysql

#  dashboard:
#    build: ./dashboard
#    ports:
#      - "8501:8501"
#    depends_on:
#      - mysql

volumes:
  mysql-data:
  minio_data:
