version: "3.8"

services:
  api_colmeia:
    build: ./api_simulador
    ports:
      - "8000:8000"
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    restart: unless-stopped

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped


  ingest_api:
    build: ./ingest
    command: python consumer_api.py
    volumes:
      - ./ingest/json:/app/ingest/json
      - ./ingest/csv:/app/ingest/csv
      - ./ingest/bd_json:/app/ingest/bd_json
    depends_on:
      - api_colmeia
      - kafka
      - minio
    restart: unless-stopped

  mysql:
    image: bitnami/mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=colmeia
      - MYSQL_USER=colmeia_user
      - MYSQL_PASSWORD=colmeia_pass

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/bitnami/mysql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    ports:
      - "8081:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          server:
            servlet:
              context-path: /
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: "kafka:9092"
    depends_on:
      - kafka

  processing_csv_kafka:
    build: ./datalake/processing_csv
    command: python3 consumer_transform_csv.py
    depends_on:
      - kafka
      - minio
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: dados_csv
    volumes:
      - ./datalake/processing_csv/saida:/app/processing_csv/saida
    restart: unless-stopped

  processing_json_kafka:
    build: ./datalake/processing_json
    command: python consumer_transform_json.py
    depends_on:
      - kafka
      - minio
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: dados_json
    volumes:
      - ./datalake/processing_json/saida:/app/processing_json/saida
    restart: unless-stopped

  processing_bd_kafka:
    build: ./datalake/processing_bd
    command: python3 consumer_transform_bd.py
    depends_on:
      - kafka
      - minio
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: dados_bd
    volumes:
      - ./datalake/processing_bd/saida:/app/processing_bd/saida
    restart: unless-stopped

#  airflow:
#    build: ./airflow
#    ports:
#      - "8080:8080"
#    depends_on:
#      - kafka
#      - mysql

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./datalake/processing_csv/saida:/app/processing_csv/saida
      - ./datalake/processing_json/saida:/app/processing_json/saida
      - ./datalake/processing_bd/saida:/app/processing_bd/saida
    restart: unless-stopped


volumes:
  mysql_data:
  minio_data: